### ISSUE TITLE
I'd like to back to vim when I typed ":TigGrep" 

### ISSUE THREAD

**Issue by nakamuta918** [iberianpig/tig-explorer.vim#10]
Hi!
I typed ":TigGrep" then "Pattern:" is displayed on the command line.
I couldn't cancel If I'd like to back to vim. 

Thank you for creating!

**Comment by iberianpig** [comment]
fix with 1c0b85ef37e239eeea63a8b2868ca861a4c7b7be
Please update tig-explorer.vim.

**Comment by nakamuta918** [comment]
Thank you!
