### ISSUE TITLE
Hangs in gvim

### ISSUE THREAD

**Issue by gauteh** [iberianpig/tig-explorer.vim#11]
Is the plugin supposed to work in gvim? tig works fine if I run it with `:terminal tig`.

**Comment by iberianpig** [comment]
It doesn't support on gvim. 
Could you make PR if you can?

**Comment by gauteh** [comment]
Ok, I dont have the chance at the moment.

**Comment by kiryph** [comment]
It does not work in most recent release (snapshot 155) of [MacVim](https://github.com/macvim-dev/macvim) with `+terminal` either.

@iberianpig Can you shortly mention what code parts have to be changed?

This is not obvious to me.

**Comment by iberianpig** [comment]
If you extend for MacVim, you may check following codes written for NeoVim.

https://github.com/iberianpig/tig-explorer.vim/blob/706ab380aff17ffcf3f5734dfe19000c05b8f57e/autoload/tig_explorer.vim#L148

**Comment by kiryph** [comment]
MacVim has nothing to do with neovim. It is like gvim for macOS.
MacVim is a graphical frontend for vim.

I think the problem of neovim with `:Bclose` is not the problem of macvim.

**Comment by iberianpig** [comment]
I understand it.
Now, tig-explorer.vim is not using `term`.
Because this plugin was originally written in a version without term (vim 8.0 and earlier).

To implement for MacVim or Gvim, you should try to use `term` in `if has('gui_macvim')` or `has('gui_running')` statement.

**Comment by iberianpig** [comment]
it works with https://github.com/iberianpig/tig-explorer.vim/pull/15 .
