### ISSUE TITLE
Got errors when first open tig-explorer in vim: Invalid argument & Undefined variables

### ISSUE THREAD

**Issue by solomonxie** [iberianpig/tig-explorer.vim#24]
Just upgraded tig-explorer and got these messages only at the first time I open tig-explorer in vim. After this, it works fine in the same vim session. Any insights? Thanks!

BTW, my environment is:
- nvim 0.4.3
- Python3.7
- MacOS
- tig 2.4.1
- tig-explorer latest commit: ae0d30c

```
Error detected while processing /Users/someone/dotfiles/vim/plugged/tig-explorer.vim/autoload/tig_explorer.vim:
line   92:
E475: Invalid argument: diff, mods, commit='HEAD', file='', lineno=0)
line   94:
E121: Undefined variable: a:file
E15: Invalid expression: a:file == ''
line  101:
E121: Undefined variable: file0
E116: Invalid arguments for function split
E15: Invalid expression: split(file0, ':')
line  102:
E121: Undefined variable: parts
E116: Invalid arguments for function len
E15: Invalid expression: len(parts) == 2
line  109:
E121: Undefined variable: a:diff
E15: Invalid expression: a:diff == '!'
line  112:
E121: Undefined variable: commit
E15: Invalid expression: commit.":".file
line  113:
E121: Undefined variable: ref
line  114:
E121: Undefined variable: ref
E116: Invalid arguments for function bufexists
E15: Invalid expression: bufexists(ref)
line  138:
E193: :endfunction not inside a function
Error detected while processing function tig_explorer#blame:
line    9:
E684: list index out of range: 0
E116: Invalid arguments for function <SNR>169_exec_tig_command
```

**Comment by iberianpig** [comment]
Thank you for reporting!

I have reproduced it.
[![Screenshot from Gyazo](https://gyazo.com/85b659675680caa7c60f762d794ed940/raw)](https://gyazo.com/85b659675680caa7c60f762d794ed940)

This issue occurs in nvim.

**Comment by iberianpig** [comment]
@solomonxie Please update tig-explorer.vim.

**Comment by solomonxie** [comment]
@iberianpig thank you so much! It worked like a charm! Appreciate your works. This plugin has been my daily tool for very long time and I constantly show off to peers how to git-blame specific people in codes. :)

**Comment by iberianpig** [comment]
@solomonxie I'm glad you said that :smile:
