### ISSUE TITLE
Encoding cyrilic text for vim-tig window

### ISSUE THREAD

**Issue by javeoff** [iberianpig/tig-explorer.vim#37]
I prefer, that terminal mode doesn't transcribe text to utf-8
this options not work
```
    encoding = 'utf-8';
    termencoding = 'utf-8';
    fileencoding = 'utf-8';
    makeencoding = 'utf-8';
```

I have this format on commits preview. It must be a cyrilic.
Default `tig` shell command works fine

<img width="1680" alt="image" src="https://user-images.githubusercontent.com/62588539/157931016-482af25d-7c0f-4c0a-a2f4-7fc0dc0b696e.png">

**Comment by iberianpig** [comment]
Which do you use Vim or NeoVim?
And, does it work `:!tig` or `:terminal tig`?

**Comment by javeoff** [comment]
Problem in default set language

`export LANG=en_US.UTF-8` - works!

**Comment by iberianpig** [comment]
@javeoff 
Did you set `export LANG=en_US.UTF-8` in .bashrc?

**Comment by javeoff** [comment]
@iberianpig 

in zshrc, yes. my LANG param was empty

**Comment by iberianpig** [comment]
I'll add it README👍
