### ISSUE TITLE
Remapping terminal non-insert mode breaks tig

### ISSUE THREAD

**Issue by ghomem** [iberianpig/tig-explorer.vim#43]
I've been maintaining this VIM configuration:

https://logical.li/blog/IDEalization-of-Vim/

which uses tig for reviewing git repositories. So, 1 million thanks for this plugin :-)

I found out that remapping the exit from terminal insert mode with this line, in .vimrc:

```
tnoremap <Esc> <C-\><C-n>
```

breaks tig-explorer causing this error

> "E21: Cannot make changes, 'modifiable' is off"

Systems in question are running Ubuntu 22.04 which include  8.2.3995-1ubuntu2.17.

This is the full vimrc:

https://gist.github.com/ghomem/816ac97ef7ccd1064e2ffa650b9033e8

The particular line is commented for now:

https://gist.github.com/ghomem/816ac97ef7ccd1064e2ffa650b9033e8#file-vimrc-L136

It is a pity to not be able to use escape in the terminal as it really improves the ergonomics.

Thank you :-)

**Comment by ghomem** [comment]
ouch.. this seems to be a vim issue:

https://github.com/vim/vim/issues/2216

workaround:

https://github.com/vim/vim/issues/2216#issuecomment-337566816

**Comment by iberianpig** [comment]
I see, so this was a Vim issue.

**Comment by ghomem** [comment]
Yes, sorry for the noise @iberianpig . And thanks again, this is an excellent plugin.
