### ISSUE TITLE
Neovim support

### ISSUE THREAD

**Issue by samuelallan72** [iberianpig/tig-explorer.vim#5]
Currently this doesn't work on Neovim. :cry:  The reason is that terminal applications launched by `:! <appname>` can't accept interactive input on stdin:

 			The command runs in a non-interactive shell connected
			to a pipe (not a terminal). Use |:terminal| to run an
			interactive shell connected to a terminal.

A neat solution would be to use the builtin terminal in vim8/neovim to launch tig instead, similar to how fzf-vim works.

**Comment by iberianpig** [comment]
@swalladge tig-explorer supports NeoVim.
