### ISSUE TITLE
Don't hardcode temporary paths

### ISSUE THREAD

**Issue by samuelallan72** [iberianpig/tig-explorer.vim#6]
Currently the following paths are hardcoded in the plugin:

- `/tmp/.tigrc`
- `/tmp/tig_explorer_current_file`

This will cause issues where `/tmp` isn't writable, multiple users on the same system use this plugin, etc.

A better solution would be use something like `tempname()` to generate a filename that will be guaranteed to be secure and writable.

**Comment by iberianpig** [comment]
fix with latest version :+1:
