### ISSUE TITLE
It does not work if the path to start vim is other than project root.

### ISSUE THREAD

**Issue by areph** [iberianpig/tig-explorer.vim#7]
Hi.
If the path that starts vim is not the project root, the following occurs.

- When you open a file in Tig by executing the Tig command, the path becomes a new file
- Error when TigBlame command is executed
   - `tig: No blame exist for #{Relative path of the current directory}#{Absolute path opened in Vim}`

This product is awesome. Thanks:)

**Comment by iberianpig** [comment]
@areph Thanks!
I fixed it. Please update the plugin and confirm to solve it, then close this issue.

**Comment by iberianpig** [comment]
@areph Have you still had the problem?

**Comment by areph** [comment]
@iberianpig I had no problem, Thanks!
