### ISSUE TITLE
Should be working even if tigrc is not found

### ISSUE THREAD

**Issue by wookayin** [iberianpig/tig-explorer.vim#9]
Even when tigrc is not found it should be working using a sensible default setting without error messages.

```
Error detected while processing function <SNR>176_initialize:
line   18:
tigrc is not found
```

**Comment by iberianpig** [comment]
tig-explore searchs tigrc from user's config (home dir or xdg-config) and system's config (/etc/tigrc).

Where is tigrc on your environment?

**Comment by wookayin** [comment]
Nowhere. I could manage to have `tigrc` somewhere proper, but it would be great to support systems where `tigrc` is never configured without any annoying error messages.

**Comment by iberianpig** [comment]
Ok.  Should be working if you don't have tigrc anywhere. 
I'll fix it. Thanks!
